In [2]:
#Tabel Logika AND 2 input
"""
x1  x2  y
1   1   1
1   0   0
0   1   0
0   0   0
"""

'\nx1  x2  y\n1   1   1\n1   0   0\n0   1   0\n0   0   0\n'

In [3]:
# library ML
import keras
import numpy as np

# model
model = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])

#model compile
model.compile(optimizer='sgd', loss='mean_squared_error')

In [4]:
# set data
xs = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=int)
ys = np.array([0, 0, 0, 1], dtype=int)

In [5]:
# tampilkan arsitektur awal
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [6]:
weights = model.get_weights()
weights

[array([[0.9732801],
        [1.2346028]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
# traing
model.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 2s 2s/step - loss: 0.9826
Epoch 2/500
1/1 [==============================] - 0s 2ms/step - loss: 0.9275
Epoch 3/500
1/1 [==============================] - 0s 74ms/step - loss: 0.8759
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 0.8275
Epoch 5/500
1/1 [==============================] - 0s 1ms/step - loss: 0.7820
Epoch 6/500
1/1 [==============================] - 0s 2ms/step - loss: 0.7395
Epoch 7/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6995
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6621
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 0.6270
Epoch 10/500
1/1 [==============================] - 0s 2ms/step - loss: 0.5940
Epoch 11/500
1/1 [==============================] - 0s 2ms/step - loss: 0.5632
Epoch 12/500
1/1 [==============================] - 0s 2ms/step - loss: 0.5342
Epoch 13/500
1/1 [==============================] - 0s 2ms/st

In [9]:
data = [1, 1]
answer = model.predict(np.array([data]))
print(answer)

[[0.79521286]]


In [11]:
weights = model.get_weights()
weights

[array([[0.5448953],
        [0.5662118]], dtype=float32),
 array([-0.31589428], dtype=float32)]

In [2]:
# library ML
import keras
import numpy as np

# model
model2 = keras.Sequential([keras.layers.Dense(units=1, input_shape=[2])])

#model compile
model2.compile(optimizer='sgd', loss='mean_squared_error')

In [3]:
# set data
xs = np.array([[2, 3], [4, 1], [5, 4], [7, 5], [8, 2], [2, 1], [4, 9], [8, 2], [7, 1], [6, 5], [1, 1], [3, 2]], dtype=int)
ys = np.array([16, 12, 28, 34, 24, 8, 44, 24, 18, 32, 6, 14], dtype=int)

In [4]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [5]:
weights = model2.get_weights()
weights

[array([[-0.93620694],
        [ 0.0392704 ]], dtype=float32),
 array([0.], dtype=float32)]

In [6]:
# traing
model2.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 824.4229
Epoch 2/500
1/1 [==============================] - 0s 3ms/step - loss: 55.7530
Epoch 3/500
1/1 [==============================] - 0s 3ms/step - loss: 12.7992
Epoch 4/500
1/1 [==============================] - 0s 2ms/step - loss: 8.7865
Epoch 5/500
1/1 [==============================] - 0s 3ms/step - loss: 7.1579
Epoch 6/500
1/1 [==============================] - 0s 2ms/step - loss: 5.9139
Epoch 7/500
1/1 [==============================] - 0s 3ms/step - loss: 4.9010
Epoch 8/500
1/1 [==============================] - 0s 2ms/step - loss: 4.0729
Epoch 9/500
1/1 [==============================] - 0s 2ms/step - loss: 3.3957
Epoch 10/500
1/1 [==============================] - 0s 3ms/step - loss: 2.8417
Epoch 11/500
1/1 [==============================] - 0s 3ms/step - loss: 2.3887
Epoch 12/500
1/1 [==============================] - 0s 2ms/step - loss: 2.0181
Epoch 13/500
1/1 [==============================] - 0s 2ms

In [7]:
# test
data = [2, 3]
answer = model2.predict(np.array([data]))
print(answer)

[[16.221134]]


In [21]:
weights = model2.get_weights()
weights

[array([[1.9934723],
        [4.024843 ]], dtype=float32),
 array([0.135672], dtype=float32)]